name: kasvo_kasir
description: Aplikasi kasir Kasvo - Multi Platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database - Cross Platform
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+1 # Untuk Windows/Linux
  path: ^1.9.0

  # Network & Connectivity
  connectivity_plus: ^7.1.1
  http: ^1.1.0
  uuid: ^4.2.1

  # Local Storage
  shared_preferences: ^2.2.2

  # UI & Localization
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

  # Mobile-only plugins (akan diabaikan di Windows)
  permission_handler: ^12.0.1 # Android only
  geolocator: ^14.0.2 # Limited Windows support

  # Printer (optional - mobile only)
  flutter_thermal_printer: ^2.0.1 # Android/iOS only

  # Image processing (cross-platform)
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon/kasvo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/kasvo.png"

  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/icon/kasvo.png"
